workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - test

variables:
  CONAN_HOME: "${CI_PROJECT_DIR}/.conan2"

test-on-macos-x86_64:
  stage: test
  tags:
    - macos-x86
  script:
    - echo "Start Test On MacOS x86_64"
    - make -f Makefile.gitlabci all
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .conan2/

test-on-macos-arm64:
  stage: test
  tags:
    - macos-arm64
  script:
    - echo "Start Test On MacOS arm64"
    - make -f Makefile.gitlabci all
    - make -f Makefile.gitlabci all TARGET_PROFILE=ios
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .conan2/

test-on-windows:
  stage: test
  tags:
    - windows
  script:
    - echo "Start Test On Windows"
    - make -f Makefile.gitlabci all
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .conan2/

test-on-linux:
  stage: test
  image: registry-dev.youle.game/misc/conanbuilder:latest
  tags:
    - docker4raven
  script:
    - echo "Start Test On Linux"
    - make -f Makefile.gitlabci all
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .conan2/
