workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - build

variables:
  CONAN_HOME: "${CI_PROJECT_DIR}/.conan2"

build-on-macos-arm64:
  stage: build
  tags:
    - macos-arm64
  script:
    - echo "Start build On MacOS arm64"
    - make -f Makefile.gitlabci eofcheck
    - make -f Makefile.gitlabci all
    - make -f Makefile.gitlabci all TARGET_PROFILE=ios

build-on-windows:
  stage: build
  tags:
    - windows
  script:
    - echo "Start build On Windows"
    - git config --global --list
    - make -f Makefile.gitlabci eofcheck
    - make -f Makefile.gitlabci all
    # - git config --global core.autocrlf input
    # - git config --global --list
    # - git rm -rf --cached .
    # - git reset --hard HEAD
    # - file Foundation/include/Poco/ASCIIEncoding.h
  variables:
    # so I can make sure the files are checked out with right eol setting.
    GIT_STRATEGY: clone

build-on-macos-x86_64:
  stage: build
  tags:
    - macos-x86
  script:
    - echo "Start build On MacOS x86_64"
    - make -f Makefile.gitlabci all


build-on-linux:
  stage: build
  image: registry-dev.youle.game/misc/conanbuilder:latest
  tags:
    - docker
  script:
    - echo "Start build On Linux"
    - make -f Makefile.gitlabci all

build-for-android:
  stage: build
  image: registry-dev.youle.game/misc/conanbuilder:latest
  tags:
    - docker
  script:
    - echo "Start build On Linux"
    - make -f Makefile.gitlabci all TARGET_PROFILE=android

build-for-android-armv7:
  stage: build
  image: registry-dev.youle.game/misc/conanbuilder:latest
  tags:
    - docker
  script:
    - echo "Start build On Linux"
    - make -f Makefile.gitlabci all TARGET_PROFILE=android_armv7

