workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - test

variables:
  CONAN_HOME: "${CI_PROJECT_DIR}/.conan2"

test-on-macos:
  stage: test
  tags:
    - macos
  script:
    - echo "Start Test On MacOS"
    - wget https://nexus.youle.game/repository/raw/conan/conan-2.3.0-macos-x86_64.tgz -O /tmp/conan-2.3.0-macos-x86_64.tgz
    - cd $HOME && tar zxf /tmp/conan-2.3.0-macos-x86_64.tgz
    - $HOME/bin/conan profile detect -e
    - $HOME/bin/conan remote add --insecure -f youle http://192.168.212.47:9300
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .conan2/

test-on-windows:
  stage: test
  tags:
    - windows
  script:
    - echo "Start Test On Windows"
    - pwd
    - curl -o conan.zip https://git.youle.game/opensource/thirdparty/poco/uploads/f109f4e0b49606c811feee5932e597a4/conan-2.3.0-windows-x86_64.zip
    - unzip conan.zip
    - ./conan.exe profile detect -e
    - ./conan.exe remote add --insecure -f youle http://192.168.212.47:9300
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .conan2/

test-on-linux:
  stage: test
  image: registry-dev.youle.game/misc/conanbuilder:latest
  tags:
    - docker
  script:
    - echo "Start Test On Linux"
    - /root/bin/conan profile detect -e
    - /root/bin/conan remote add --insecure -f youle http://192.168.212.47:9300
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .conan2/
