workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - test

test-on-macos:
  stage: test
  tags:
    - macos
  script:
    - echo "Start Test On MacOS"
    - wget https://nexus.youle.game/repository/raw/conan/conan-2.3.0-macos-x86_64.tgz -O /tmp/conan-2.3.0-macos-x86_64.tgz
    - cd $HOME && tar zxf /tmp/conan-2.3.0-macos-x86_64.tgz
    - $HOME/bin/conan --version

test-on-windows:
  stage: test
  tags:
    - windows
  script:
    - echo "Start Test On Windows"
    - powershell -Command 'Invoke-WebRequest -Uri "https://nexus.youle.game/repository/raw/conan/conan-2.3.0-windows-x86_64.zip" -OutFile conan-2.3.0-windows-x86_64.zip'
    - powershell -Command 'Expand-Archive .\conan-2.3.0-windows-x86_64.zip -DestinationPath .'
    - powershell -Command '.\conan.exe --version'

# test-on-linux:
#   stage: test
#   image: registry-dev.youle.game/frontend/raven-test:20240410
#   tags:
#     - docker
#   script:
#     - echo "Start Test On Linux"
#     - wget https://nexus.youle.game/repository/raw/conan/conan-2.3.0-linux-x86_64.tgz -O /tmp/conan-2.3.0-linux-x86_64.tgz
#     - cd $HOME && tar zxf /tmp/conan-2.3.0-linux-x86_64.tgz
#     - $HOME/bin/conan --version
