workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - build

variables:
  CONAN_HOME: "${CI_PROJECT_DIR}/.conan2"

# build-on-macos-x86_64:
#   stage: build
#   tags:
#     - macos-x86
#   script:
#     - echo "Start build On MacOS x86_64"
#     - make -f Makefile.gitlabci all
#   cache:
#     key: ${CI_COMMIT_REF_SLUG}
#     paths:
#       - .conan2/

# build-on-macos-arm64:
#   stage: build
#   tags:
#     - macos-arm64
#   script:
#     - echo "Start build On MacOS arm64"
#     - make -f Makefile.gitlabci all
#     - make -f Makefile.gitlabci all TARGET_PROFILE=ios
#   cache:
#     key: ${CI_COMMIT_REF_SLUG}
#     paths:
#       - .conan2/

build-on-windows:
  stage: build
  tags:
    - windows
  script:
    - echo "Start build On Windows"
    - file Foundation/CMakeLists.txt
    - file Foundation/include/Poco/ASCIIEncoding.h
    - cat .gitattributes
    - git config --global --list
    - git config --system --list
    - git config --local --list
    - git rm -rf --cached .
    - git reset --hard HEAD
    - file Foundation/CMakeLists.txt
    - file Foundation/include/Poco/ASCIIEncoding.h

  # cache:
  #   key: ${CI_COMMIT_REF_SLUG}
  #   paths:
  #     - .conan2/
  variables:
    # so I can make sure the files are checked out with right eol setting in .gitattributes
    GIT_STRATEGY: clone


# build-on-linux:
#   stage: build
#   image: registry-dev.youle.game/misc/conanbuilder:latest
#   tags:
#     - docker
#   script:
#     - echo "Start build On Linux"
#     - make -f Makefile.gitlabci all
#   cache:
#     key: ${CI_COMMIT_REF_SLUG}
#     paths:
#       - .conan2/

# build-for-android:
#   stage: build
#   image: registry-dev.youle.game/misc/conanbuilder:latest
#   tags:
#     - docker
#   script:
#     - echo "Start build On Linux"
#     - make -f Makefile.gitlabci all TARGET_PROFILE=android
#   cache:
#     key: ${CI_COMMIT_REF_SLUG}
#     paths:
#       - .conan2/

# build-for-android-armv7:
#   stage: build
#   image: registry-dev.youle.game/misc/conanbuilder:latest
#   tags:
#     - docker
#   script:
#     - echo "Start build On Linux"
#     - make -f Makefile.gitlabci all TARGET_PROFILE=android_armv7
#   cache:
#     key: ${CI_COMMIT_REF_SLUG}
#     paths:
#       - .conan2/
