workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - test

test-on-macos:
  stage: test
  tags:
    - macos
  script:
    - echo "Start Test On MacOS"
    - python --version
    - python -m pip --version

test-on-windows:
  stage: test
  tags:
    - windows
  script:
    - echo "Start Test On Windows"
    - python --version
    - python -m pip --version

test-on-linux:
  stage: test
  image: registry-dev.youle.game/frontend/raven-test:20240410
  tags:
    - docker
  script:
    - echo "Start Test On Linux"
    - python --version
    - python -m pip --version
